route:
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: yourmail@gmail.com
    from: yourmail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yourmail@gmail.com
    auth_identity: yourmail@gmail.com
    auth_password: secretpswd


